### ISSUE TITLE
[bug] return code is 0 on failed cmd

### ISSUE THREAD

**Issue by mzemb** [aacebedo/machination#43]
> machination start --verbose <instName>

fails and print an error

> "Unable to start machine instance '<instName>': Error while starting machine instance: '<instName>'.

But the return code transmited to bash is 0.

Problem: should change the way action are launched from argument parsing.

**Comment by aacebedo** [comment]
Done

**Comment by mzemb** [comment]
Not fixed for all cases:

> machination create --guestinterface 'eth0|192.168.3.100|auto|instA' --no-interactive --verbose myTemplate:1.0 instA

fails with a raise InvalidCmdLineArgument
but returns an error code of 0 to the shell.
